version: '3.9'
services:
  donkey-container:
    image: donkey-cuda-jupyterlab
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-modeset
    ports:
      - "8888:8888"
      - "8887:8887"
    shm_size: '64M'
    volumes:
      - /home/local_sqs-ai/airace:/app/airace
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
